# permissions for end users to view profiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: profile-viewer-role
rules:
- apiGroups:
  - kustomize.fluxcd.io
  resources:
  - profiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kustomize.fluxcd.io
  resources:
  - profiles/status
  verbs:
  - get
